package com.github.lapesd.rdfit.components.converters.quad;

import javax.annotation.Nonnull;
import java.util.Objects;

/**
 * Pair-like data structure that represents a graph and a triple.
 * This should be generated by a function compatible with the {@link QuadSplitter} interface
 */
public class SplitQuad {
    private final @Nonnull String graph;
    private final @Nonnull Object triple;

    public SplitQuad(@Nonnull String graph, @Nonnull Object triple) {
        this.graph = graph;
        this.triple = triple;
    }

    public @Nonnull String getGraph() {
        return graph;
    }

    public @Nonnull Object getTriple() {
        return triple;
    }

    @Override public String toString() {
        return String.format("(%s, %s)", getGraph(), getTriple());
    }

    @Override public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SplitQuad)) return false;
        SplitQuad splitQuad = (SplitQuad) o;
        return getGraph().equals(splitQuad.getGraph()) && getTriple().equals(splitQuad.getTriple());
    }

    @Override public int hashCode() {
        return Objects.hash(getGraph(), getTriple());
    }
}
